### ISSUE TITLE
"Upgrade to MML v. 8.1.12_5.74.1441" Panic

### ISSUE THREAD

**Issue by ghost** [digama0/mizar-rs#3]
```
Upgrade to MML v. 8.1.12_5.74.1441
"The verifier mostly works on the new MML out of the box, which is good,
although they seem to have come up with new and unusual ways to torture
the verifier in this edition and some of the new articles have managed
to beat the record for longest check time. Some profiling is needed, and
possibly some quadratic algorithms need to be revisited."
```
Indeed,
ok. Confirmation (DEBUG=1 & RUST_BACKTRACE=1) by :

```
$ cat analyze-mml.sh
#!/bin/sh
DEBUG=1 RUST_BACKTRACE=1 DEP_ORDER=1 XML_EXPORT=1 NO_ANALYZER=1 NO_CHECKER=1 cargo run --release
echo 'copying prel/ files to mizshare/prel/'
cp -r miz/prel/* miz/mizshare/prel/
rm -rf miz/prel
```

Results:

```
$ ./analyze-mml.sh
    Finished release [optimized + debuginfo] target(s) in 0.02s
     Running `target/release/miz-rs`
   0: tarski   in 0.004s                                                                
   2: boole    in 0.006s                                                                
   1: xboole_0 in 0.006s                                                                
   6: xfamily  in 0.011s                                                                
   5: xtuple_0 in 0.011s                                                                
   3: xboole_1 in 0.017s                                                                
   4: enumset1 in 0.018s                                                                
   7: xregular in 0.018s                                                                
thread '<unnamed>' panicked at '824:27: expected Keyword(Proof)', src/parser/miz.rs:1270:15
stack backtrace:
   8: zfmisc_1 in 0.035s                                                                
   0: rust_begin_unwindubset   | relat_1  | subset_1 | funct_1  | grfunc_1 | setfam_1 | 
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: miz_rs::parser::miz::Scanner::accept
             at ./src/parser/miz.rs:363:5
   3: miz_rs::parser::miz::Parser::parse_scheme
             at ./src/parser/miz.rs:1270:5
   4: miz_rs::parser::miz::Parser::parse_items
             at ./src/parser/miz.rs:1926:70
   5: miz_rs::analyze::<impl miz_rs::reader::Reader>::run_analyzer
             at ./src/analyze.rs:70:15
   6: miz_rs::reader::<impl miz_rs::MizPath>::with_reader
             at ./src/reader.rs:347:5
   7: miz_rs::main::{{closure}}::{{closure}}::{{closure}}
             at ./src/main.rs:3248:15
   8: std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
   9: std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  10: std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  11: miz_rs::main::{{closure}}::{{closure}}
             at ./src/main.rs:3217:34
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: 9: subset_1 panicked
   9: subset_1 in 0.050s                                                                
ordinal1 | relat_2  | subset   | relat_1  | wellord1 | funct_1  | grfunc_1 | setfam_1 | 
panic: 1                                   
```
mizar-rs regression: Previous commit (4c944b25865343e05099ce4e92583f09f642a093), no panic but warning.
Mizar system 8.1.11 -> 8.1.12
Waiting for a new patch :-)

**Comment by digama0** [comment]
You should re-run `./download-mml.sh`, that commit also updated the patch file and the following lines are relevant:
```diff
--- mml/subset_1.miz
+++ mml/subset_1.miz
@@ -824 +824,2 @@
-  in X iff x in A() & P[x];
+  in X iff x in A() & P[x]
+proof
```
That said the work on 5.74 is still ongoing, I (or you) can move master back to the previous commit and put the upgrade on a feature branch if required. (AFAIK there is only one actual failure, in `number07` which has some huge performance issues, and I haven't had time to track it down yet. The entire rest of the MML should work ATM.)

**Comment by ghost** [comment]
```quote
I (or you) can move master back to the previous commit and put the upgrade on a feature branch if required
the work on 5.74 is still ongoing
```
ok I'm waiting no problem. 

I remember that I had to change some parameters in the mobject.pas file to compile this version of the MML

https://github.com/MizarProject/system/blob/main/base/mobjects.pas

MaxSize = 2000000;
instead of
MaxSize = 200000;

https://github.com/MizarProject/system/blob/main/kernel/limits.pas
MaxTheoNbr = 20000;
instead of
MaxTheoNbr = 2000;

I didn't have time to push this from my MizarSystem fork.
